defaultNamespace: bigbang

helm:
  chart: git::https://repo1.dso.mil/platform-one/big-bang/bigbang.git@chart?ref=v1.32.0
  releaseName: bigbang
  valuesFrom:
  - configMapKeyRef:
      name: bigbang-configs
      namespace: fleet-default
      key: values.yaml
  # - secretKeyRef:
  #     name: bigbang-secrets
  #     namespace: bigbang
  #     key: values.yaml