defaultNamespace: bigbang

helm:
  chart: git::https://github.com/DoD-Platform-One/big-bang.git@chart?ref=v1.32.0
  releaseName: bigbang
  valuesFrom:
  - configMapKeyRef:
      name: istio-config
      namespace: fleet-default
      key: values.yaml
  # - secretKeyRef:
  #     name: bigbang-secrets
  #     namespace: bigbang
  #     key: values.yaml