apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: bigbang-gitrepos
  namespace: fleet-local
spec:
  repo: https://github.com/atoy3731/fleet-bigbang-umbrella.git
  targets:
  - clusterSelector:
      matchExpressions:
      - key: provider.cattle.io
        operator: NotIn
        values:
        - harvester
  paths:
  - gitrepos/
