apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: bigbang-prereqs
  namespace: fleet-default
spec:
  repo: ssh://git@git-ssh.atoy.lol/home/bigbang.git
  clientSecretName: private-key
  targets:
  - name: local
    clusterSelector:
      matchLabels:
        cluster: local
  paths:
  - ./umbrella/resources/configs
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: bigbang-umbrella
  namespace: fleet-default
spec:
  repo: ssh://git@git-ssh.atoy.lol/home/bigbang.git
  clientSecretName: private-key
  targets:
  - name: local
    clusterSelector:
      matchLabels:
        cluster: local
  paths:
  - ./umbrella/resources/gitrepos