apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: bigbang-umbrella
  namespace: fleet-local
spec:
  repo: ssh://git@git-ssh.atoy.lol/home/bigbang.git
  clientSecretName: private-key
  # targets:
  # - name: local
  #   clusterSelector:
  #     matchLabels:
  #       cluster: local
  paths:
  - ./umbrella
