apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: flux
  namespace: fleet-default
spec:
  repo: ssh://git@git-ssh.atoy.lol/home/bigbang.git
  clientSecretName: private-key
  targets:
  - name: test
    clusterSelector:
      matchLabels:
        cluster: test
  paths:
  - helm/flux/manifests/
