defaultNamespace: bigbang

helm:
  chart: git::https://github.com/DoD-Platform-One/big-bang.git//chart
  releaseName: bigbang
  valuesFrom:
  - configMapKeyRef:
      name: istio-config
      namespace: bigbang
      key: values.yaml
  # - secretKeyRef:
  #     name: bigbang-secrets
  #     namespace: bigbang
  #     key: values.yaml

dependsOn:
  - name: flux-helm-flux-manifests