defaultNamespace: bigbang

helm:
  chart: git::https://github.com/DoD-Platform-One/big-bang.git//chart
  releaseName: bigbang
  valuesFrom:
  - configMapKeyRef:
      name: bigbang-configs
      namespace: bigbang
      key: values.yaml
  - secretKeyRef:
      name: bigbang-secrets
      namespace: bigbang
      key: values.yaml

dependsOn:
  - name: flux-helm-flux-manifests

diff:
  comparePatches:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: istio-operator
    namespace: bigbang
    operations:
      - { "op": "remove", "path": "/metadata/labels" }
      - { "op": "remove", "path": "/spec/chart/spec/interval" }
      - { "op": "remove", "path": "/spec/interval" }
      - { "op": "remove", "path": "/spec/rollback/cleanupOnFail" }
      - { "op": "remove", "path": "/spec/rollback/timeout" }
      - { "op": "remove", "path": "/spec/test/enable" }
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: istio
    namespace: bigbang
    operations:
      - { "op": "remove", "path": "/metadata/labels" }
      - { "op": "remove", "path": "/spec/chart/spec/interval" }
      - { "op": "remove", "path": "/spec/interval" }
      - { "op": "remove", "path": "/spec/rollback/cleanupOnFail" }
      - { "op": "remove", "path": "/spec/rollback/timeout" }
      - { "op": "remove", "path": "/spec/test/enable" }

# GitRepositories
  - apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    name: istio-controlplane
    namespace: bigbang
    operations:
      - { "op": "remove", "path": "/metadata/labels" }
      - { "op": "remove", "path": "/spec/interval" }
  - apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    name: istio-operator
    namespace: bigbang
    operations:
      - { "op": "remove", "path": "/metadata/labels" }
      - { "op": "remove", "path": "/spec/interval" }
  - apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    name: monitoring
    namespace: bigbang
    operations:
      - { "op": "remove", "path": "/metadata/labels" }
      - { "op": "remove", "path": "/spec/interval" }

# Namespaces
  - apiVersion: v1
    kind: Namespace
    name: istio-operator
    operations:
      - { "op": "remove", "path": "/metadata/labels" }
  - apiVersion: v1
    kind: Namespace
    name: monitoring
    operations:
      - { "op": "remove", "path": "/metadata/labels" }
  - apiVersion: v1
    kind: Namespace
    name: istio-system
    operations:
      - { "op": "remove", "path": "/metadata/labels" }

# Secrets
  - apiVersion: v1
    kind: Secret
    name: private-registry
    namespace: istio-system
    operations:
      - { "op": "remove", "path": "/metadata/labels" }
  - apiVersion: v1
    kind: Secret
    name: private-registry
    namespace: monitoring
    operations:
      - { "op": "remove", "path": "/metadata/labels" }
  - apiVersion: v1
    kind: Secret
    name: private-registry
    namespace: istio-operator
    operations:
      - { "op": "remove", "path": "/metadata/labels" }