apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bigbang-secrets
  namespace: bigbang
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: private-key
    creationPolicy: Owner
  data:
  - secretKey: foo
    remoteRef:
      key: bigbang/data/repo1-cred
      property: data.foo