apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bigbang-secrets
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      key: test/bigbang
      property: reg1_email
    secretKey: reg1_email
  - remoteRef:
      conversionStrategy: Default
      key: test/bigbang
      property: reg1_username
    secretKey: reg1_username
  - remoteRef:
      conversionStrategy: Default
      key: test/bigbang
      property: reg1_password
    secretKey: reg1_password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: bigbang-secrets
    template:
      type: Opaque
      data:
        values.yaml: |-
          registryCredentials:
            username: "{{ .reg1_username | toString }}"
            password: "{{ .reg1_password | toString }}"
            email: "{{ .reg1_email | toString }}"